version: "3.9"

services:
  nginx: 
    image: nginx
    container_name: nginx_c
    ports: 
      - 4001:4001
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: nginx -g "daemon off;"

  flutter:
    build: ./flutter
    container_name: flutter_c
    ports:
      - 4002:4002
    command: flutter run -d web-server --web-hostname 0.0.0.0 --web-port 4002 --web-renderer html 
    stdin_open: true 
    tty: true 

  fastapi:
    container_name: fastapi_c
    build: ./fastapi
    ports:
      - 4003:4003
    volumes:
      - ./fastapi:/workspace
    command: uvicorn main:app --reload --host=0.0.0.0 --port=4003